[package]
name = "mirame"
version = "0.1.0"
edition = "2021"
authors = ["Rohit Prakash <rohitp934@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "mirame"
path = "src/main.rs"

[dependencies]
